




# .streamlit/secrets.toml
[mysql]
host = "remote.runflare.com"
port = 30655
database = "meyarmyszuu_db"
user = "root"
password = "9d4m3votkyqfhma"






private_gsheets_url = "https://docs.google.com/spreadsheets/d/1zX0B7Iztun5l86Tj9zvaoPGz12InsUSCgI-na5aMN_s/edit?usp=sharing"

[gcp_service_account]
type = "service_account"
project_id = "avid-factor-361909"
private_key_id = "cb845b9c424bebccb9c518b05f36706666393a86"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQC+AIahJ1fv2weu\ne7t/6t0IIwBiLwdkrG0kwif1RHrvAty0I063JUWj4iDmEnpAOp23a91X2E3ACQT0\nIsfBXnGI1U+MK9qan4dxP6g7QjcCKuL8PWc6FqzB5Nc4kLEQUCSGw7OvuMlzVTX7\n3WhJrjt9kwKIX+8BmQ7/JC+gInsgkgxx60g+IOy8wnpDeW93RH/6OFmRuM4AX1Tw\nwtVK8uX3ZYFOFNyainpwbrYx5I/vuyd47mhzzC92golVSNBgV497CNVfWqmbKr9i\n8H/aaR6I41vJNWHRNwD5UQgCCQDTB6pYA1leBiDHVzr5agBqTcD/cATq3qVlJsw5\nX999oclDAgMBAAECggEAR5icIqrYLKZs+Rdf+p5OZuwFj3noP8vnntPYycfhySHb\nd7fcSBAv80bZHck1rvFHkCABusHj3mqnprVab2e+wZCb1paJ2/0kRQz3QEk9wD/X\n47Phq5Zyx+eLICIJzrtcYDnrglpP8vlXi86NJ0KT4UhdynTX89Kwv3zrw1xq6ETo\nwJmZT1Om8JavLKMtdMGIQ/AWzaPLd4vod22Ie36o+TWaGfaqBQYVp3z+X6DOiwLg\nri0FItTvcAWnww1sxpEs3+YXjHTv7v9LFSusiuQSU7Tzwo/z0kG9k1mx6UAQeWty\nO2wJsFvdtkgzo7H6aJtH6ktKxg5mc5mrbicxFscR5QKBgQD9apG3fHnY6qNSKEP5\nxwqOubsOC1xf5Z2xnqNl7HKLknfLJRvZPUkiBDdqvqF6H2NWqAGXHeK5s4+Uz1Ns\nMxBm3i2au5OWSwu2eyKcUhS7quFXXttAYR3nzSbNi1+l6o3zVXfT8/AwvVokr+6l\n2z50j0/QBPCe/NTkP5gZ/ILT1QKBgQC/8HEk+q2HFKv8GnV0cfN+ORblBAUVNylH\nm2Q7TedM/0ld5/0yM8iwzgEshW/6znJjOod+oUIlUIkg1OqbZJEiBN3Y2rQTQbMM\ncij66GSA4+SdGunIQ9/7YlYTL7MWMg0B7E/PcjUD1PSqUClkTrLouA4d5vWc8O+G\nW8QkC4TstwJ/TjOUxAqlj0rZG4FReMLzfxfRoYPf/bfd8fICenF855VLYmURMvi2\nmMi0UTyCmC0XeqZd10Rhsuy2YjWYiMs5RIVLjXRVFwwRkT5ub87klwUkhNHA1x0h\nHWcxkjxwR8MaCv1U/RNKC8BjEO85tfTyUQXom0jq+CUNjWISjfJebQKBgDXALt9N\nOCU4+8TY4AWhF7BEao3t50J+tRexg4s8EMc2QqSCoBxb9hrVRezi3W4ePFhffqxO\nmoh6mjxQg/bKXf5p4HqnHIC8CFk26xUA2YxixZXdgJSttV7ftf0fgYZ4s73TILKW\naBRPocjENCM8CswzJvjmweeWbW1x62awtyPXAoGBANc+qWbZMeh2ROrbXkbd7ljB\ncUQpcEzv4TvTcUJJ0+bvqojxzDDPPZAR00utVkZ3J/+9ZD4xfh9ox2fjRhJQ0x4z\nEfUoiiMRTdli3Op9KpP2U+dX3vFc+AIK3GNEkyAEjbw//ZwXtpwm98tVBuZPM0E6\nuppZym3E9/hpiazx1uCF\n-----END PRIVATE KEY-----\n"
client_email = "meyar-729@avid-factor-361909.iam.gserviceaccount.com"
client_id = "110656191045790305039"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/meyar-729%40avid-factor-361909.iam.gserviceaccount.com"



